openapi: 3.1.0
info:
  title: BrightEdge Platform accounts page crawl API
  description: This API provides the ability to integrate with BrightEdge Platform
  version: 5.0.0
tags:
- name: page crawl
paths:
  /5.0/marketo/page_crawl:
    post:
      tags:
      - page crawl
      summary: This API retrieves page html by crawling a given url
      operationId: crawl_page_content_5_0_marketo_page_crawl_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoCacheRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/marketo/page_crawl:
    post:
      tags:
      - page crawl
      summary: This API retrieves page html by crawling a given url
      operationId: crawl_page_content_latest5_marketo_page_crawl_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoCacheRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /5.0/dataset/page_crawl:
    post:
      tags:
      - page crawl
      summary: This API retrieves page html by crawling a given url
      operationId: crawl_page_content_5_0_dataset_page_crawl_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoCacheRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/dataset/page_crawl:
    post:
      tags:
      - page crawl
      summary: This API retrieves page html by crawling a given url
      operationId: crawl_page_content_latest5_dataset_page_crawl_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoCacheRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
components:
  schemas:
    MarketoCacheRequest:
      properties:
        url:
          type: string
          minLength: 1
          title: Url
      type: object
      required:
      - url
      title: MarketoCacheRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    http_basic:
      type: http
      scheme: basic
    forwarded_http_basic:
      type: apiKey
      in: header
      name: X-Forwarded-Authorization
    session_cookie:
      type: apiKey
      in: cookie
      name: BRIGHTEDGE
    session_header:
      type: apiKey
      in: header
      name: X-BRIGHTEDGE-SESSION
    api_token_header:
      type: apiKey
      in: header
      name: X-Token
    bearer_token:
      type: apiKey
      in: header
      name: Bearer-Token
