openapi: 3.2.0
info:
  title: BrightEdge Platform Keywords API
  description: This API provides the ability to integrate with BrightEdge Platform
  version: 5.0.0
tags:
- name: Keywords
  description: Operation related to keywords
paths:
  /5.0/objects/brandfilters/{account_id}:
    get:
      tags:
      - Keywords
      summary: This call returns a string of bql filters for branded keywords
      operationId: get_brand_filters_keywords_for_account_5_0_objects_brandfilters__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      - required: false
        schema:
          type: boolean
          title: Branded
          default: true
        name: branded
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandFiltersOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/objects/brandfilters/{account_id}:
    get:
      tags:
      - Keywords
      summary: This call returns a string of bql filters for branded keywords
      operationId: get_brand_filters_keywords_for_account_latest5_objects_brandfilters__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      - required: false
        schema:
          type: boolean
          title: Branded
          default: true
        name: branded
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandFiltersOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /5.0/objects/keywords/{account_id}:
    get:
      tags:
      - Keywords
      summary: This call returns a list of keywords of the given account
      operationId: get_account_keywords_5_0_objects_keywords__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/KeywordOut'
                type: array
                title: Response Get Account Keywords 5 0 Objects Keywords  Account Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/objects/keywords/{account_id}:
    get:
      tags:
      - Keywords
      summary: This call returns a list of keywords of the given account
      operationId: get_account_keywords_latest5_objects_keywords__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/KeywordOut'
                type: array
                title: Response Get Account Keywords Latest5 Objects Keywords  Account Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /5.0/objects/keywordgroups/{account_id}/{keyword_group_id}:
    get:
      tags:
      - Keywords
      summary: This call returns a list of keywords within the give keyword group
      operationId: get_account_keywordgroup_detail_5_0_objects_keywordgroups__account_id___keyword_group_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      - required: true
        schema:
          type: integer
          title: Keyword Group Id
        name: keyword_group_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeywordGroupDetailOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
    post:
      tags:
      - Keywords
      summary: '[WIP] This call adds a list of keywords to the give keyword group'
      operationId: add_kw_to_kwg_in_account_5_0_objects_keywordgroups__account_id___keyword_group_id__post
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      - required: true
        schema:
          type: integer
          title: Keyword Group Id
        name: keyword_group_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              items:
                additionalProperties:
                  type: string
                type: object
              type: array
              title: Kw List
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/objects/keywordgroups/{account_id}/{keyword_group_id}:
    get:
      tags:
      - Keywords
      summary: This call returns a list of keywords within the give keyword group
      operationId: get_account_keywordgroup_detail_latest5_objects_keywordgroups__account_id___keyword_group_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      - required: true
        schema:
          type: integer
          title: Keyword Group Id
        name: keyword_group_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeywordGroupDetailOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
    post:
      tags:
      - Keywords
      summary: '[WIP] This call adds a list of keywords to the give keyword group'
      operationId: add_kw_to_kwg_in_account_latest5_objects_keywordgroups__account_id___keyword_group_id__post
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      - required: true
        schema:
          type: integer
          title: Keyword Group Id
        name: keyword_group_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              items:
                additionalProperties:
                  type: string
                type: object
              type: array
              title: Kw List
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    KeywordGroupDetailOut:
      properties:
        id:
          type: integer
          title: Id
        name:
          type: string
          title: Name
        keywords:
          items:
            $ref: '#/components/schemas/KeywordOut'
          type: array
          title: Keywords
      type: object
      required:
      - id
      - name
      - keywords
      title: KeywordGroupDetailOut
    KeywordOut:
      properties:
        id:
          type: integer
          title: Id
        name:
          type: string
          title: Name
      type: object
      required:
      - id
      - name
      title: KeywordOut
    BrandFiltersOut:
      properties:
        bql_filters:
          type: string
          title: Bql Filters
        keywords:
          items:
            additionalProperties:
              anyOf:
              - type: string
              - type: integer
              - type: string
                format: date-time
            type: object
          type: array
          title: Keywords
      type: object
      required:
      - bql_filters
      - keywords
      title: BrandFiltersOut
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    http_basic:
      type: http
      scheme: basic
    forwarded_http_basic:
      type: apiKey
      in: header
      name: X-Forwarded-Authorization
    session_cookie:
      type: apiKey
      in: cookie
      name: BRIGHTEDGE
    session_header:
      type: apiKey
      in: header
      name: X-BRIGHTEDGE-SESSION
    api_token_header:
      type: apiKey
      in: header
      name: X-Token
    bearer_token:
      type: apiKey
      in: header
      name: Bearer-Token
