openapi: 3.2.0
info:
  title: BrightEdge Platform Keywordgroups API
  description: This API provides the ability to integrate with BrightEdge Platform
  version: 5.0.0
tags:
- name: keywordgroups
  description: Operation related to keyword groups
paths:
  /5.0/objects/keywordgroups/activity/{group_name}:
    get:
      tags:
      - keywordgroups
      summary: This call returns list of keyword activities per account
      operationId: get_keywords_activity_5_0_objects_keywordgroups_activity__group_name__get
      parameters:
      - required: true
        schema:
          type: string
          title: Group Name
        name: group_name
        in: path
      - required: false
        schema:
          type: integer
          maximum: 202605.0
          minimum: 202210.0
          title: Start Year Month
          default: 202605
        name: start_year_month
        in: query
      - required: false
        schema:
          type: integer
          maximum: 202606.0
          minimum: 202211.0
          title: End Year Month
          default: 202606
        name: end_year_month
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/KeywordActivityOut'
                type: array
                title: Response Get Keywords Activity 5 0 Objects Keywordgroups Activity  Group Name  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /5.0/objects/keywordgroups/{account_id}:
    get:
      tags:
      - keywordgroups
      summary: This call returns a list of keyword groups of the given account
      operationId: get_account_keywordgroups_5_0_objects_keywordgroups__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/KeywordGroupOut'
                type: array
                title: Response Get Account Keywordgroups 5 0 Objects Keywordgroups  Account Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/objects/keywordgroups/activity/{group_name}:
    get:
      tags:
      - keywordgroups
      summary: This call returns list of keyword activities per account
      operationId: get_keywords_activity_latest5_objects_keywordgroups_activity__group_name__get
      parameters:
      - required: true
        schema:
          type: string
          title: Group Name
        name: group_name
        in: path
      - required: false
        schema:
          type: integer
          maximum: 202605.0
          minimum: 202210.0
          title: Start Year Month
          default: 202605
        name: start_year_month
        in: query
      - required: false
        schema:
          type: integer
          maximum: 202606.0
          minimum: 202211.0
          title: End Year Month
          default: 202606
        name: end_year_month
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/KeywordActivityOut'
                type: array
                title: Response Get Keywords Activity Latest5 Objects Keywordgroups Activity  Group Name  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/objects/keywordgroups/{account_id}:
    get:
      tags:
      - keywordgroups
      summary: This call returns a list of keyword groups of the given account
      operationId: get_account_keywordgroups_latest5_objects_keywordgroups__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/KeywordGroupOut'
                type: array
                title: Response Get Account Keywordgroups Latest5 Objects Keywordgroups  Account Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    KeywordGroupOut:
      properties:
        id:
          type: integer
          title: Id
        name:
          type: string
          title: Name
      type: object
      required:
      - id
      - name
      title: KeywordGroupOut
    KeywordActivityOut:
      properties:
        account_id:
          type: integer
          title: Account Id
        keyword_change_rate:
          type: number
          title: Keyword Change Rate
      type: object
      required:
      - account_id
      - keyword_change_rate
      title: KeywordActivityOut
  securitySchemes:
    http_basic:
      type: http
      scheme: basic
    forwarded_http_basic:
      type: apiKey
      in: header
      name: X-Forwarded-Authorization
    session_cookie:
      type: apiKey
      in: cookie
      name: BRIGHTEDGE
    session_header:
      type: apiKey
      in: header
      name: X-BRIGHTEDGE-SESSION
    api_token_header:
      type: apiKey
      in: header
      name: X-Token
    bearer_token:
      type: apiKey
      in: header
      name: Bearer-Token
