openapi: 3.1.0
info:
  title: BrightEdge Platform accounts domains API
  description: This API provides the ability to integrate with BrightEdge Platform
  version: 5.0.0
tags:
- name: domains
  description: Operation related to domains
paths:
  /5.0/objects/competitors/{account_id}:
    get:
      tags:
      - domains
      summary: This call returns a competitors for given account id
      operationId: get_account_competitors_5_0_objects_competitors__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CompetitorOut'
                type: array
                title: Response Get Account Competitors 5 0 Objects Competitors  Account Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/objects/competitors/{account_id}:
    get:
      tags:
      - domains
      summary: This call returns a competitors for given account id
      operationId: get_account_competitors_latest5_objects_competitors__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CompetitorOut'
                type: array
                title: Response Get Account Competitors Latest5 Objects Competitors  Account Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /5.0/objects/domains:
    get:
      tags:
      - domains
      summary: This call returns a list of primary domains for accounts that the user has access to.
      operationId: get_user_domains_5_0_objects_domains_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/DomainOut'
                type: array
                title: Response Get User Domains 5 0 Objects Domains Get
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /5.0/objects/domains/{account_id}:
    get:
      tags:
      - domains
      summary: This call returns a primary domain for given account id
      operationId: get_account_domain_5_0_objects_domains__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/objects/domains:
    get:
      tags:
      - domains
      summary: This call returns a list of primary domains for accounts that the user has access to.
      operationId: get_user_domains_latest5_objects_domains_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/DomainOut'
                type: array
                title: Response Get User Domains Latest5 Objects Domains Get
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/objects/domains/{account_id}:
    get:
      tags:
      - domains
      summary: This call returns a primary domain for given account id
      operationId: get_account_domain_latest5_objects_domains__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /3.0/objects/domains:
    get:
      tags:
      - domains
      summary: This call returns a list of primary domains for accounts that the user has access to.
      operationId: get_user_domains_3_0_objects_domains_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyCompetitorDomainOut'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /3.0/objects/domains/{account_id}:
    get:
      tags:
      - domains
      summary: This call returns a primary domain for given account id
      operationId: get_account_domain_3_0_objects_domains__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyCompetitorDomainOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest3/objects/domains:
    get:
      tags:
      - domains
      summary: This call returns a list of primary domains for accounts that the user has access to.
      operationId: get_user_domains_latest3_objects_domains_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyCompetitorDomainOut'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest3/objects/domains/{account_id}:
    get:
      tags:
      - domains
      summary: This call returns a primary domain for given account id
      operationId: get_account_domain_latest3_objects_domains__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyCompetitorDomainOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /3.0/objects/competitors/{account_id}:
    get:
      tags:
      - domains
      summary: This call returns a competitors for given account id
      operationId: get_account_competitors_3_0_objects_competitors__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyCompetitorDomainOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest3/objects/competitors/{account_id}:
    get:
      tags:
      - domains
      summary: This call returns a competitors for given account id
      operationId: get_account_competitors_latest3_objects_competitors__account_id__get
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyCompetitorDomainOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
components:
  schemas:
    CompetitorOut:
      properties:
        id:
          type: integer
          title: Id
        name:
          type: string
          title: Name
      type: object
      required:
      - id
      - name
      title: CompetitorOut
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    LegacyDomainShortOut:
      properties:
        id:
          type: string
          title: Id
        domain:
          type: string
          title: Domain
      type: object
      required:
      - id
      - domain
      title: LegacyDomainShortOut
    DomainOut:
      properties:
        id:
          type: integer
          title: Id
        account_id:
          type: integer
          title: Account Id
        name:
          type: string
          title: Name
      type: object
      required:
      - id
      - account_id
      - name
      title: DomainOut
    LegacyCompetitorDomainOut:
      properties:
        domains:
          items:
            $ref: '#/components/schemas/LegacyDomainShortOut'
          type: array
          title: Domains
      type: object
      required:
      - domains
      title: LegacyCompetitorDomainOut
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
  securitySchemes:
    http_basic:
      type: http
      scheme: basic
    forwarded_http_basic:
      type: apiKey
      in: header
      name: X-Forwarded-Authorization
    session_cookie:
      type: apiKey
      in: cookie
      name: BRIGHTEDGE
    session_header:
      type: apiKey
      in: header
      name: X-BRIGHTEDGE-SESSION
    api_token_header:
      type: apiKey
      in: header
      name: X-Token
    bearer_token:
      type: apiKey
      in: header
      name: Bearer-Token
