openapi: 3.1.0
info:
  title: BrightEdge Platform accounts top pages API
  description: This API provides the ability to integrate with BrightEdge Platform
  version: 5.0.0
tags:
- name: top pages
paths:
  /5.0/marketo/top_pages:
    post:
      tags:
      - top pages
      summary: This API retrieves top N(default 1000) pages for a given base domain
      operationId: get_top_pages_5_0_marketo_top_pages_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoTopPagesRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketoTopPagesResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/marketo/top_pages:
    post:
      tags:
      - top pages
      summary: This API retrieves top N(default 1000) pages for a given base domain
      operationId: get_top_pages_latest5_marketo_top_pages_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoTopPagesRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketoTopPagesResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /5.0/dataset/top_pages:
    post:
      tags:
      - top pages
      summary: This API retrieves top N(default 1000) pages for a given base domain
      operationId: get_top_pages_5_0_dataset_top_pages_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoTopPagesRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketoTopPagesResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/dataset/top_pages:
    post:
      tags:
      - top pages
      summary: This API retrieves top N(default 1000) pages for a given base domain
      operationId: get_top_pages_latest5_dataset_top_pages_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoTopPagesRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketoTopPagesResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
components:
  schemas:
    MarketoTopPagesRequest:
      properties:
        collector_id:
          type: integer
          title: Collector Id
          default: 34
        domain:
          type: string
          minLength: 1
          title: Domain
        limit:
          type: integer
          maximum: 1000.0
          exclusiveMinimum: 0.0
          title: Limit
          default: 1000
      type: object
      required:
      - domain
      title: MarketoTopPagesRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    MarketoTopPagesResponseDataItem:
      properties:
        url:
          type: string
          title: Url
        search_vol:
          type: integer
          title: Search Vol
        average_rank:
          type: integer
          title: Average Rank
        est_visits:
          type: integer
          title: Est Visits
      type: object
      title: MarketoTopPagesResponseDataItem
    MarketoResponseInfo:
      properties:
        version:
          type: string
          title: Version
        timestamp:
          type: number
          title: Timestamp
      type: object
      required:
      - version
      - timestamp
      title: MarketoResponseInfo
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    MarketoTopPagesResponse:
      properties:
        status:
          type: boolean
          title: Status
        message:
          type: string
          title: Message
        info:
          $ref: '#/components/schemas/MarketoResponseInfo'
        data:
          $ref: '#/components/schemas/MarketoTopPagesResponseData'
      type: object
      required:
      - status
      - message
      - info
      - data
      title: MarketoTopPagesResponse
    MarketoTopPagesResponseData:
      properties:
        pages:
          items:
            $ref: '#/components/schemas/MarketoTopPagesResponseDataItem'
          type: array
          title: Pages
      type: object
      title: MarketoTopPagesResponseData
  securitySchemes:
    http_basic:
      type: http
      scheme: basic
    forwarded_http_basic:
      type: apiKey
      in: header
      name: X-Forwarded-Authorization
    session_cookie:
      type: apiKey
      in: cookie
      name: BRIGHTEDGE
    session_header:
      type: apiKey
      in: header
      name: X-BRIGHTEDGE-SESSION
    api_token_header:
      type: apiKey
      in: header
      name: X-Token
    bearer_token:
      type: apiKey
      in: header
      name: Bearer-Token
