openapi: 3.2.0
info:
  title: BrightEdge Platform Accounts API
  description: This API provides the ability to integrate with BrightEdge Platform
  version: 5.0.0
tags:
- name: Accounts
  description: Operation related to accounts
paths:
  /5.0/objects/accounts:
    get:
      tags:
      - Accounts
      summary: This call returns the list of accounts this user can access
      operationId: get_all_accounts_5_0_objects_accounts_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/AccountOut'
                type: array
                title: Response Get All Accounts 5 0 Objects Accounts Get
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /5.0/objects/accounts/{account_id}:
    post:
      tags:
      - Accounts
      summary: This call returns the details of an individual account
      operationId: get_account_5_0_objects_accounts__account_id__post
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountIdIn'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountIdOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/objects/accounts:
    get:
      tags:
      - Accounts
      summary: This call returns the list of accounts this user can access
      operationId: get_all_accounts_latest5_objects_accounts_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/AccountOut'
                type: array
                title: Response Get All Accounts Latest5 Objects Accounts Get
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/objects/accounts/{account_id}:
    post:
      tags:
      - Accounts
      summary: This call returns the details of an individual account
      operationId: get_account_latest5_objects_accounts__account_id__post
      parameters:
      - required: true
        schema:
          type: integer
          title: Account Id
        name: account_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountIdIn'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountIdOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
components:
  schemas:
    AccountOut:
      properties:
        id:
          type: integer
          title: Id
        name:
          type: string
          title: Name
        created_on:
          type: string
          format: date-time
          title: Created On
      type: object
      required:
      - id
      - name
      - created_on
      title: AccountOut
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    AccountIdOut:
      properties:
        account_name:
          type: string
          title: Account Name
        account_id:
          type: integer
          title: Account Id
        created_on_date:
          type: string
          format: date-time
          title: Created On Date
        account_primary_domain_tracked:
          type: string
          title: Account Primary Domain Tracked
        GA_integration_setup:
          type: boolean
          title: Ga Integration Setup
        GSC_integration_setup:
          type: boolean
          title: Gsc Integration Setup
        GA_integrated_profile_id:
          type: string
          title: Ga Integrated Profile Id
        GSC_integrated_sites:
          items:
            type: string
          type: array
          title: Gsc Integrated Sites
        facebook_integration_setup:
          type: boolean
          title: Facebook Integration Setup
        facebook_fan_page_integrated:
          type: string
          title: Facebook Fan Page Integrated
        number_of_keywords_allocated:
          type: integer
          title: Number Of Keywords Allocated
        number_of_keywords_used:
          type: integer
          title: Number Of Keywords Used
        number_of_unused_keywords:
          type: integer
          title: Number Of Unused Keywords
        number_of_allocated_competitors:
          type: integer
          title: Number Of Allocated Competitors
        number_of_tracked_competitors:
          type: integer
          title: Number Of Tracked Competitors
        number_of_unused_competitors:
          type: integer
          title: Number Of Unused Competitors
        number_of_keywords_with_PLPs_default_SE:
          type: integer
          title: Number Of Keywords With Plps Default Se
        number_of_keywords_with_PLPs_all_tracked_SE:
          type: integer
          title: Number Of Keywords With Plps All Tracked Se
        last_logged_into_date_for_the_account:
          type: string
          format: date-time
          title: Last Logged Into Date For The Account
      type: object
      required:
      - account_name
      - account_id
      - created_on_date
      - account_primary_domain_tracked
      - GA_integration_setup
      - GSC_integration_setup
      - GA_integrated_profile_id
      - GSC_integrated_sites
      - facebook_integration_setup
      - facebook_fan_page_integrated
      - number_of_keywords_allocated
      - number_of_keywords_used
      - number_of_unused_keywords
      - number_of_allocated_competitors
      - number_of_tracked_competitors
      - number_of_unused_competitors
      - number_of_keywords_with_PLPs_default_SE
      - number_of_keywords_with_PLPs_all_tracked_SE
      title: AccountIdOut
    AccountIdIn:
      properties:
        excluded_keyword_group_filter:
          items:
            type: string
          type: array
          title: Excluded Keyword Group Filter
      type: object
      title: AccountIdIn
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    http_basic:
      type: http
      scheme: basic
    forwarded_http_basic:
      type: apiKey
      in: header
      name: X-Forwarded-Authorization
    session_cookie:
      type: apiKey
      in: cookie
      name: BRIGHTEDGE
    session_header:
      type: apiKey
      in: header
      name: X-BRIGHTEDGE-SESSION
    api_token_header:
      type: apiKey
      in: header
      name: X-Token
    bearer_token:
      type: apiKey
      in: header
      name: Bearer-Token
