openapi: 3.1.0
info:
  title: BrightEdge Platform accounts top keywords for a domain API
  description: This API provides the ability to integrate with BrightEdge Platform
  version: 5.0.0
tags:
- name: top keywords for a domain
paths:
  /5.0/marketo/top_keywords:
    post:
      tags:
      - top keywords for a domain
      summary: This API retrieves top N(default 100) keywords for a given domain
      operationId: get_top_keywords_per_domain_5_0_marketo_top_keywords_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoTopKeywordsPerDomainRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketoTopKeywordsPerDomainResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/marketo/top_keywords:
    post:
      tags:
      - top keywords for a domain
      summary: This API retrieves top N(default 100) keywords for a given domain
      operationId: get_top_keywords_per_domain_latest5_marketo_top_keywords_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoTopKeywordsPerDomainRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketoTopKeywordsPerDomainResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /5.0/dataset/top_keywords:
    post:
      tags:
      - top keywords for a domain
      summary: This API retrieves top N(default 100) keywords for a given domain
      operationId: get_top_keywords_per_domain_5_0_dataset_top_keywords_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoTopKeywordsPerDomainRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketoTopKeywordsPerDomainResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
  /latest5/dataset/top_keywords:
    post:
      tags:
      - top keywords for a domain
      summary: This API retrieves top N(default 100) keywords for a given domain
      operationId: get_top_keywords_per_domain_latest5_dataset_top_keywords_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketoTopKeywordsPerDomainRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketoTopKeywordsPerDomainResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - http_basic: []
      - forwarded_http_basic: []
      - session_cookie: []
      - session_header: []
      - api_token_header: []
      - bearer_token: []
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    MarketoResponseInfo:
      properties:
        version:
          type: string
          title: Version
        timestamp:
          type: number
          title: Timestamp
      type: object
      required:
      - version
      - timestamp
      title: MarketoResponseInfo
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    MarketoTopKeywordsPerDomainResponseData:
      properties:
        keywords:
          items:
            $ref: '#/components/schemas/MarketoTopKeywordsPerDomainResponseDataItem'
          type: array
          title: Keywords
      type: object
      title: MarketoTopKeywordsPerDomainResponseData
    MarketoTopKeywordsPerDomainRequest:
      properties:
        collector_id:
          type: integer
          title: Collector Id
          default: 34
        domain:
          type: string
          minLength: 1
          title: Domain
        limit:
          type: integer
          maximum: 1000.0
          exclusiveMinimum: 0.0
          title: Limit
          default: 100
      type: object
      required:
      - domain
      title: MarketoTopKeywordsPerDomainRequest
    MarketoTopKeywordsPerDomainResponseDataItem:
      properties:
        keyword:
          type: string
          title: Keyword
        volume:
          type: integer
          title: Volume
        blended_rank:
          type: integer
          title: Blended Rank
        est_visits:
          type: integer
          title: Est Visits
        top_url:
          type: string
          title: Top Url
      type: object
      title: MarketoTopKeywordsPerDomainResponseDataItem
    MarketoTopKeywordsPerDomainResponse:
      properties:
        status:
          type: boolean
          title: Status
        message:
          type: string
          title: Message
        info:
          $ref: '#/components/schemas/MarketoResponseInfo'
        data:
          $ref: '#/components/schemas/MarketoTopKeywordsPerDomainResponseData'
      type: object
      required:
      - status
      - message
      - info
      - data
      title: MarketoTopKeywordsPerDomainResponse
  securitySchemes:
    http_basic:
      type: http
      scheme: basic
    forwarded_http_basic:
      type: apiKey
      in: header
      name: X-Forwarded-Authorization
    session_cookie:
      type: apiKey
      in: cookie
      name: BRIGHTEDGE
    session_header:
      type: apiKey
      in: header
      name: X-BRIGHTEDGE-SESSION
    api_token_header:
      type: apiKey
      in: header
      name: X-Token
    bearer_token:
      type: apiKey
      in: header
      name: Bearer-Token
